=== bijeshcnair/cordyshttpcon/docs/external/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://httpconnector.coe.cordys.com/2.0/configuration"
	targetNamespace="http://httpconnector.coe.cordys.com/2.0/configuration" elementFormDefault="qualified">
	<element name="configurations" type="tns:ctConfigurations"></element>

	<complexType name="ctConfigurations">
		<sequence>
			<element name="connections" type="tns:ctConnections"
				maxOccurs="1" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="ctConnections">
		<sequence>
			<element name="connection" type="tns:ctConnection" maxOccurs="unbounded"
				minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="ctConnection">
		<sequence>
			<element name="url" type="anyURI" maxOccurs="1" minOccurs="1">
				<annotation>
					<documentation>
						The base URL for the URL
					</documentation>
				</annotation>
			</element>
			<element name="timeout" type="long" maxOccurs="1" minOccurs="0">
				<annotation>
					<documentation>
						The timeout to use. If not specified the default
						timeout of 30000 ms is used.
					</documentation>
				</annotation>
			</element>
			<element name="username" type="string" maxOccurs="1"
				minOccurs="0">
				<annotation>
					<documentation>
						The optional username to use for logging on to
						the
						service
					</documentation>
				</annotation>
			</element>
			<element name="password" type="string" maxOccurs="1"
				minOccurs="0">
				<annotation>
					<documentation>
						The optional password for logging on to the
						given
						service
					</documentation>
				</annotation>
			</element>
			<element name="proxy-host" type="string" maxOccurs="1"
				minOccurs="0">
				<annotation>
					<documentation>
						The optional proxy server to use before
						connecting to
						this server.
					</documentation>
				</annotation>
			</element>
			<element name="proxy-port" type="int" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="proxy-username" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="proxy-password" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="check-certificate" type="boolean" maxOccurs="1"
				minOccurs="0">
				<annotation>
					<documentation>
						Whether or not the validity of the certificates
						should be checked
					</documentation>
				</annotation>
			</element>
			<element name="authenticate-always" type="boolean" maxOccurs="1"
				minOccurs="0">
				<annotation>
					<documentation>
						Whether or not explicit authentication should be
						done for everycall.
					</documentation>
				</annotation>
			</element>
			<element name="parameters" type="tns:ctParameters" maxOccurs="1"
				minOccurs="0">
			</element>
		</sequence>
		<attribute name="id" type="string" use="required"></attribute>
	</complexType>

	<complexType name="ctParameters">
		<sequence>
			<element name="parameter" type="tns:ctParameter" maxOccurs="unbounded"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="ctParameter">
		<sequence>
			<element name="name" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="value" type="tns:ctValue" maxOccurs="1"
				minOccurs="1">
			</element>
		</sequence>
		<attribute name="type" type="tns:stParameterType" use="optional" default="string"></attribute>
	</complexType>


	<complexType name="ctValue" mixed="true">
		<sequence>
			<any minOccurs="0" maxOccurs="unbounded" processContents="skip"></any>
		</sequence>
	</complexType>

    <simpleType name="stParameterType">
    	<restriction base="string">
    	<enumeration value="string"/>
    	<enumeration value="xml"/>
    	<enumeration value="encoded"/>
    	</restriction>
    </simpleType>
</schema>

=== bijeshcnair/cordyshttpcon/tags/3.0.0/HTTPConnector_Test/test/java/com/cordys/coe/ac/httpconnector/jira/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:configurations
	xmlns:tns="http://httpconnector.coe.cordys.com/2.0/configuration"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://httpconnector.coe.cordys.com/2.0/configuration ../../../../../../../../docs/external/configuration.xsd ">
	<tns:connections>
		<tns:connection id="JIRA">
			<tns:url>http://cnl1259:8080</tns:url>
			<tns:parameters>
				<tns:parameter type="string">
					<tns:name>jira_username</tns:name>
					<tns:value>pgussow</tns:value>
				</tns:parameter>
				<tns:parameter type="encoded">
					<tns:name>jira_password</tns:name>
					<tns:value>cGd1c3Nvdw==</tns:value>
				</tns:parameter>
			</tns:parameters>
		</tns:connection>
	</tns:connections>
</tns:configurations>

=== bijeshcnair/cordyshttpcon/tags/3.0.0/docs/external/example-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:configurations xmlns:tns="http://httpconnector.coe.cordys.com/2.0/configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://httpconnector.coe.cordys.com/2.0/configuration configuration.xsd ">
  <tns:connections>
    <tns:connection id="">
      <tns:url>http://tempuri.org</tns:url>
      <tns:timeout>0</tns:timeout>
      <tns:username>tns:username</tns:username>
      <tns:password>tns:password</tns:password>
      <tns:proxy-host>tns:proxy-host</tns:proxy-host>
      <tns:proxy-port>0</tns:proxy-port>
      <tns:proxy-username>tns:proxy-username</tns:proxy-username>
      <tns:proxy-password>tns:proxy-password</tns:proxy-password>
      <tns:check-certificate>true</tns:check-certificate>
      <tns:authenticate-always>true</tns:authenticate-always>
      <tns:parameters>
        <tns:parameter type="string">
          <tns:name>tns:name</tns:name>
          <tns:value/>
        </tns:parameter>
      </tns:parameters>
    </tns:connection>
  </tns:connections>
</tns:configurations>
