=== bijeshcnair/cordyshttpcon/tags/2.0.3-dev/docs/external/implementation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema elementFormDefault="qualified"
    targetNamespace="http://httpconnector.coe.cordys.com/2.0/implementation"
    xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://httpconnector.coe.cordys.com/2.0/implementation">
    <annotation>
        <documentation>This schema holds the definition of the method
			implementations for the HttpConnector.</documentation>
    </annotation>
    <element name="implementation" type="tns:ctImplementation"/>
    <element name="xslt" type="string">
        <annotation>
            <documentation>Holds the path to an xslt which is in the XML Store
			</documentation>
        </annotation>
    </element>
    <complexType name="ctImplementation">
        <sequence>
            <element maxOccurs="1" minOccurs="1" name="connection-id" type="string">
                <annotation>
                    <documentation>
						The ID of the connection that should be used.
					</documentation>
                </annotation>
            </element>
            <element maxOccurs="1" minOccurs="0" name="uri" type="anyURI">
                <annotation>
                    <documentation>
						The URI that should be called
					</documentation>
                </annotation>
            </element>
            <element maxOccurs="1" minOccurs="0"
                name="clean-response-body" type="boolean">
                <annotation>
                    <documentation>
						If true, the response SOAP body contents will be
						cleared. This is useful only for methods which
						cannot return the
						response method element.
					</documentation>
                </annotation>
            </element>
            <element default="POST" maxOccurs="1" minOccurs="0"
                name="http-method" type="tns:stHttpMethod">
                <annotation>
                    <documentation>
						Holds the HTTP method that should be used
					</documentation>
                </annotation>
            </element>
            <element maxOccurs="1" minOccurs="1" name="request-handler" type="tns:ctHandler"/>
            <element maxOccurs="1" minOccurs="1" name="response-handler" type="tns:ctHandler"/>
            <element maxOccurs="1" minOccurs="0"
                name="valid-response-xpath" type="string">
                <annotation>
                    <documentation>
						Optional XPath expression for validating the
						response
					</documentation>
                </annotation>
            </element>
            <element maxOccurs="1" minOccurs="0"
                name="valid-response-code" type="int">
                <annotation>
                    <documentation>
						Optional HTTP response code for validating the
						response.
					</documentation>
                </annotation>
            </element>
            <element maxOccurs="1" minOccurs="0" name="namespaces" type="tns:ctNamespaces">
                <annotation>
                    <documentation>Holds the namespace prefix mappings that should be
						used.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
    <simpleType name="stHttpMethod">
        <restriction base="string">
            <enumeration value="GET"/>
            <enumeration value="POST"/>
            <enumeration value="PUT"/>
            <enumeration value="DELETE"/>
        </restriction>
    </simpleType>
    <complexType name="ctHandler">
        <sequence>
            <any maxOccurs="unbounded" minOccurs="0" processContents="skip"/>
        </sequence>
        <attribute name="class" type="string" use="required"/>
    </complexType>
    <complexType name="ctNamespaces">
        <sequence>
            <element maxOccurs="unbounded" minOccurs="1" name="binding" type="tns:ctBinding"/>
        </sequence>
    </complexType>
    <complexType name="ctBinding">
        <attribute name="prefix" type="string" use="required"/>
        <attribute name="uri" type="string" use="required"/>
    </complexType>
    <complexType name="ctRestRequestHandler">
        <annotation>
            <documentation>For the RestRequestHandler the class should be set to
				com.cordys.coe.ac.httpconnector.impl.RestRequestHandler
			</documentation>
        </annotation>
        <sequence>
            <element maxOccurs="1" minOccurs="0" ref="tns:xslt"/>
            <element maxOccurs="1" minOccurs="1" name="uri-parameters" type="tns:ctURIParameters"/>
        </sequence>
        <attribute
            fixed="com.cordys.coe.ac.httpconnector.impl.RestRequestHandler"
            name="class" type="string" use="required"/>
    </complexType>
    <complexType name="ctStandardRequestHandler">
        <annotation>
            <documentation>For the StandardRequestHandler the class should be set
				to
				com.cordys.coe.ac.httpconnector.impl.StandardRequestHandler
			</documentation>
        </annotation>
        <sequence>
            <element ref="tns:xslt">
                <annotation>
                    <documentation>The XSLT to apply to the request</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute
            fixed="com.cordys.coe.ac.httpconnector.impl.StandardRequestHandler"
            name="class" type="string" use="required"/>
    </complexType>
    <complexType name="ctURIParameters">
        <sequence>
            <element maxOccurs="unbounded" minOccurs="1"
                name="parameter" type="tns:ctResUriParameter"/>
        </sequence>
    </complexType>
    <complexType mixed="true" name="ctResUriParameter">
        <attribute name="type" type="tns:ctUriParameterType"/>
    </complexType>
    <simpleType name="ctUriParameterType">
        <restriction base="string">
            <enumeration value="xpath"/>
            <enumeration value="connection-uri"/>
            <enumeration value="fixed"/>
            <enumeration value="connection-parameter"/>
        </restriction>
    </simpleType>
    <element name="rest-request-handler" type="tns:ctRestRequestHandler"/>
    <element name="standard-request-handler" type="tns:ctStandardRequestHandler"/>
    <element name="standard-response-handler" type="tns:ctStandardResponseHandler"/>
    <complexType name="ctStandardResponseHandler">
        <sequence>
            <element maxOccurs="1" minOccurs="0" ref="tns:xslt">
                <annotation>
                    <documentation>The XSLT to apply to the response</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute
            fixed="com.cordys.coe.ac.httpconnector.impl.StandardResponseHandler"
            name="class" type="string" use="required"/>
    </complexType>
    <complexType name="ctRestHtmlRequestHandler">
        <annotation>
            <documentation>For the RestHtmlRequestHandler the class should be set to com.cordys.coe.ac.httpconnector.rest.html.RestHTMLRequestHandler</documentation>
        </annotation>
        <sequence>
            <element ref="tns:xslt">
                <annotation>
                    <documentation>The XSLT to apply to the request</documentation>
                </annotation>
            </element>
            <element maxOccurs="1" minOccurs="0" name="parameters" type="tns:ctRestHTMLParameters"/>
        </sequence>
        <attribute
            fixed="com.cordys.coe.ac.httpconnector.impl.RestRequestHandler"
            name="class" type="string" use="required"/>
    </complexType>
    <complexType name="ctRestHTMLParameter">
        <sequence>
            <element default="false" maxOccurs="1" minOccurs="0"
                name="optional" type="boolean"/>
            <element maxOccurs="1" minOccurs="1" name="destination" type="tns:stRestHTMLParameterDestination"/>
            <element maxOccurs="1" minOccurs="1" name="name" type="string"/>
            <element maxOccurs="1" minOccurs="1" name="type" type="tns:stRestHTMLParameterType"/>
            <element maxOccurs="1" minOccurs="1" name="value" type="string"/>
            <element maxOccurs="1" minOccurs="0" name="default" type="string"/>
        </sequence>
    </complexType>
    <element name="rest-html-request-handler" type="tns:ctRestHtmlRequestHandler"/>
    <complexType name="ctRestHTMLParameters">
        <sequence>
            <element maxOccurs="unbounded" minOccurs="1"
                name="parameter" type="tns:ctRestHTMLParameter"/>
        </sequence>
    </complexType>
    <simpleType name="stRestHTMLParameterDestination">
        <restriction base="string">
            <enumeration value="request"/>
            <enumeration value="body"/>
        </restriction>
    </simpleType>
    <simpleType name="stRestHTMLParameterType">
        <restriction base="string">
            <enumeration value="xpath"/>
            <enumeration value="connection-uri"/>
            <enumeration value="fixed"/>
            <enumeration value="connection-parameter"/>
        </restriction>
    </simpleType>
</schema>

=== bijeshcnair/cordyshttpcon/trunk/docs/external/example-rest-request-handler.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:implementation
	xmlns:tns="http://httpconnector.coe.cordys.com/2.0/implementation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://httpconnector.coe.cordys.com/2.0/implementation implementation.xsd ">
	<tns:connection-id>JIRA</tns:connection-id>
	<tns:uri>/secure/admin/user/UserBrowser.jspa</tns:uri>
	<tns:clean-response-body>true</tns:clean-response-body>
	<tns:http-method>GET</tns:http-method>
	<tns:request-handler
		class="com.cordys.coe.ac.httpconnector.impl.RestRequestHandler">
		<tns:uri-parameters>
			<tns:parameter type="XPATH" />
		</tns:uri-parameters>
	</tns:request-handler>
	<tns:response-handler class="com.cordys.coe.ac.httpconnector.impl.StandardResponseHandler"/>
	<tns:valid-response-code>200</tns:valid-response-code>
	<tns:namespaces>
		<tns:binding prefix="ns" uri="http://httpconnector.coe.cordys.com/2.0/REST/JIRA" />
	</tns:namespaces>
</tns:implementation>

=== bijeshcnair/cordyshttpcon/trunk/docs/external/example-implementation.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:implementation xmlns:tns="http://httpconnector.coe.cordys.com/2.0/implementation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://httpconnector.coe.cordys.com/2.0/implementation implementation.xsd ">
  <tns:connection-id>tns:connection-id</tns:connection-id>
  <tns:uri>http://tempuri.org</tns:uri>
  <tns:clean-response-body>true</tns:clean-response-body>
  <tns:http-method>POST</tns:http-method>
  <tns:request-handler class=""/>
  <tns:response-handler>tns:response-handler</tns:response-handler>
  <tns:valid-response-xpath>tns:valid-response-xpath</tns:valid-response-xpath>
  <tns:valid-response-code>0</tns:valid-response-code>
  <tns:namespaces>
    <tns:binding prefix="" uri=""/>
  </tns:namespaces>
</tns:implementation>
